version: "3.9"

services:
  mongo:
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 27017:27017
    networks:
      - internal
  backend:
    build:
      context: ./backend
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    networks:
      - internal
      - api
  frontend:
    build:
      context: ./frontend
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - PORT=5173
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      backend:
        condition: service_started
    ports:
      - 5173:5173
    networks:
      - api
networks:
  internal:
  api:
